### ISSUE TITLE
Sidebar ToC highlight cues match incorrect entry after topic loads

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/feedback#3668]
**Describe the bug**

Sidebar ToC highlight cues match an incorrect entry after topic loads **_if multiple ToC entries map to the same topic_**.

Further, there's a second bug here: After the topic loads and if another (different) sidebar ToC selection is made that also maps to the same topic, **_the sidebar ToC doesn't change the existing (right or wrong) ToC highlight cue_**.

**To Reproduce**

Have two (or more) ToC entries with the same endpoint, then select the first one on the live docs site. The wrong entry receives the highlight cue (`is-selected` style).

Consider the following section of `toc.yml` file entries for two Blazor framework Razor components. They both need to map to the same destination in the docs, which resolves to:

```
https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#built-in-form-components
```

btw -- We're using groups to version our conceptual docs (folders: `3.1`, `5.0`, `6.0`). Even if we aren't using groups (i.e., before we implemented group versioning on our repo), the behavior for this issue was the same.

```yml
- name: InputRadio
  href: 3.1/blazor/forms-validation.md#built-in-form-components
- name: InputRadio
  href: 5.0/blazor/forms-validation.md#built-in-form-components
- name: InputRadio
  href: 6.0/blazor/forms-validation.md#built-in-form-components
- name: InputRadioGroup
  href: 3.1/blazor/forms-validation.md#built-in-form-components
- name: InputRadioGroup
  href: 5.0/blazor/forms-validation.md#built-in-form-components
- name: InputRadioGroup
  href: 6.0/blazor/forms-validation.md#built-in-form-components
```

Rendered ToC showing two of the prior entries [that match the correct group (version) of docs]:

<img width="237" alt="sidebar" src="https://user-images.githubusercontent.com/1622880/127664749-7dcde29e-3b01-425c-ab9f-d6e492e493ad.PNG">

**Expected behavior**

Select the `InputRadio` component in the sidebar ToC. When the topic loads, the ToC's highlight cue should reflect the reader-selected `InputRadio` choice.

**Actual behavior**

The `InputRadioGroup` entry receives the highlight cue (`is-selected` CSS style):

<img width="223" alt="sidebar2" src="https://user-images.githubusercontent.com/1622880/127664768-c3a86521-9a80-4174-be5b-cf35f3b5fd46.PNG">

For the second bug: Further selecting another (different) entry doesn't change the highlight cue. The highlight cue in this case also doesn't reflect what the reader selected.

**Desktop (please complete the following information):**

 - OS: Win10
 - Browser: FireFox
 - Version: 90.0.2

**Additional context**

You soon won't be able to find the whole node of ToC cross-links for our built-in Razor components in our `toc.yml` at:

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/toc.yml

... because I'm working on moving the whole node into a formal topic on ...

https://github.com/dotnet/AspNetCore.Docs/pull/22901

... that removes the whole node.

Also, I'm currently discussing another problem with the sidebar ToC highlight cue (`is-selected` style) and group versioning, whereby the highlight cue is only applied to the last group (version) of the docs (e.g., in our case ... `6.0 Preview` right now). The highlight cue doesn't appear at all for our earlier groups (versions) of topics (e.g., in our case ... `3.1` and `5.0`). This is under discussion offline with three DocFX engineers. I'm not sure if they've opened an internal issue for that offline discussion. I will send them a link to this issue via email. All of these `is-selected` problems might be related, or they may decide that they should all be worked together.
