### ISSUE TITLE
Bold screaming focus outline

### ISSUE THREAD

**Issue by ygoe** [MicrosoftDocs/feedback#886]
**Describe the bug**
Every clicked link has a big fat black dashed outline around it. It's three times the size of a regular keyboard focus rectangle, and also appears when I don't touch my keyboard at all.

**To Reproduce**
1. Click on a link and keep the mouse button pressed.

**Expected behavior**
No outline.

**Screenshots**
Should be visible everywhere, has been confirmed elsewhere for Firefox and Chrome.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: current stable (was it 92? the number changes every other week)

**Additional context**
If that fat outline is supposed to be a keyboard focus rectangle, then it should only appear when I'm using my keyboard to navigate. Microsoft should be very well aware of what a focus rectangle is. It should not be there when I'm using a pointer input device.

This user style can be used to get rid of most of the outlines. Some `.card` elements have it still though and I failed to analyse where they come from.

```css
.has-default-focus .is-focused,
.has-default-focus:focus:not(.visually-hidden):not(.has-inverted-focus):not(:active),
.has-default-focus :focus:not(.visually-hidden):not(.has-inverted-focus):not(:active),
.lang-toggle-container .checkbox-toggle-wrapper input[type="checkbox"]:focus + label.switch,
.this:focus
{
    outline: none;
}
```
