### ISSUE TITLE
Methods summary column width in API reference

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#936]
Original GitHub issue https://github.com/dotnet/docs/issues/1174 by @svick

The Methods summary table in API reference seems to have fixed relative column widths, which makes it look bad in some cases.

For example on [`Microsoft.CSharp.RuntimeBinder.Binder`](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder), it looks like this for me:

![](http://imgur.com/VYpU5xF.png)

I think this table would look better with the first column wider, relatively to the second column.

As far as I can tell, this is caused by the following CSS rules:

``` css
table.nameValue td:nth-child(1) {
    width: 30%;
}
table.nameValue td:nth-child(2) {
    width: 70%;
}
```

I expect there is some way to use CSS to make it look for example like this, while also ensuring other tables still look good:

![](http://imgur.com/uZthR7Q.png)

Screenshots taken using Firefox 49 on Windows 10.
